import type {
  Property,
  PropertyImage,
  PropertyAmenity,
} from "@/types/property";
import type {
  UserProfile,
  Notification,
  Message,
  Chat,
  Lead,
  Appointment,
  Review,
} from "@/types/user";

// ============================================================================
// MOCK PROPERTY IMAGES (Unsplash real estate photography)
// ============================================================================

const propertyImages: Record<string, PropertyImage[]> = {
  luxury1: [
    { id: "img-1a", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80", alt: "Modern luxury villa exterior with pool", isPrimary: true, order: 0 },
    { id: "img-1b", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80", alt: "Spacious living room interior", isPrimary: false, order: 1 },
    { id: "img-1c", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", alt: "Modern kitchen with island", isPrimary: false, order: 2 },
    { id: "img-1d", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80", alt: "Master bedroom suite", isPrimary: false, order: 3 },
  ],
  apartment1: [
    { id: "img-2a", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80", alt: "Modern apartment living area", isPrimary: true, order: 0 },
    { id: "img-2b", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80", alt: "Apartment interior with city view", isPrimary: false, order: 1 },
    { id: "img-2c", url: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&q=80", alt: "Modern bathroom", isPrimary: false, order: 2 },
  ],
  apartment2: [
    { id: "img-3a", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80", alt: "Spacious 3BHK living room", isPrimary: true, order: 0 },
    { id: "img-3b", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80", alt: "Dining area", isPrimary: false, order: 1 },
    { id: "img-3c", url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80", alt: "Bedroom with balcony view", isPrimary: false, order: 2 },
    { id: "img-3d", url: "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&q=80", alt: "Kitchen", isPrimary: false, order: 3 },
  ],
  villa1: [
    { id: "img-4a", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80", alt: "Independent villa front view", isPrimary: true, order: 0 },
    { id: "img-4b", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80", alt: "Villa garden area", isPrimary: false, order: 1 },
    { id: "img-4c", url: "https://images.unsplash.com/photo-1600566753086-00f18f6b0a56?w=800&q=80", alt: "Villa interior hall", isPrimary: false, order: 2 },
  ],
  plot1: [
    { id: "img-5a", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80", alt: "Residential plot with greenery", isPrimary: true, order: 0 },
    { id: "img-5b", url: "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80", alt: "Plot aerial view", isPrimary: false, order: 1 },
    { id: "img-5c", url: "https://images.unsplash.com/photo-1595880500386-4b33823b29cd?w=800&q=80", alt: "Surrounding area", isPrimary: false, order: 2 },
  ],
  commercial1: [
    { id: "img-6a", url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80", alt: "Modern office space", isPrimary: true, order: 0 },
    { id: "img-6b", url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80", alt: "Open plan office", isPrimary: false, order: 1 },
    { id: "img-6c", url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80", alt: "Conference room", isPrimary: false, order: 2 },
  ],
  pg1: [
    { id: "img-7a", url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", alt: "PG room interior", isPrimary: true, order: 0 },
    { id: "img-7b", url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80", alt: "Furnished room", isPrimary: false, order: 1 },
    { id: "img-7c", url: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80", alt: "Common area", isPrimary: false, order: 2 },
  ],
  farmhouse1: [
    { id: "img-8a", url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80", alt: "Luxury farmhouse exterior", isPrimary: true, order: 0 },
    { id: "img-8b", url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80", alt: "Farmhouse living room", isPrimary: false, order: 1 },
    { id: "img-8c", url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80", alt: "Farmhouse grounds", isPrimary: false, order: 2 },
  ],
};

// ============================================================================
// MOCK AMENITIES
// ============================================================================

const standardAmenities: PropertyAmenity[] = [
  { id: "power-backup", name: "Power Backup", icon: "Zap", category: "utility" },
  { id: "lift", name: "Lift", icon: "ArrowUpDown", category: "basic" },
  { id: "gated-security", name: "Gated Security", icon: "Shield", category: "safety" },
  { id: "covered-parking", name: "Covered Parking", icon: "Car", category: "parking" },
  { id: "gym", name: "Gymnasium", icon: "Dumbbell", category: "lifestyle" },
  { id: "swimming-pool", name: "Swimming Pool", icon: "Waves", category: "lifestyle" },
  { id: "park", name: "Park / Garden", icon: "Trees", category: "lifestyle" },
  { id: "cctv", name: "CCTV Surveillance", icon: "Camera", category: "safety" },
  { id: "clubhouse", name: "Clubhouse", icon: "Building2", category: "lifestyle" },
  { id: "water-supply", name: "24x7 Water Supply", icon: "Droplets", category: "utility" },
  { id: "maintenance-staff", name: "Maintenance Staff", icon: "Wrench", category: "society" },
  { id: "vastu-compliant", name: "Vastu Compliant", icon: "Compass", category: "basic" },
];

const luxuryAmenities: PropertyAmenity[] = [
  ...standardAmenities,
  { id: "ev-charging", name: "EV Charging", icon: "PlugZap", category: "parking" },
  { id: "sports-facility", name: "Sports Facility", icon: "Trophy", category: "lifestyle" },
  { id: "jogging-track", name: "Jogging Track", icon: "Footprints", category: "lifestyle" },
  { id: "indoor-games", name: "Indoor Games", icon: "Gamepad2", category: "lifestyle" },
  { id: "solar-panels", name: "Solar Panels", icon: "Sun", category: "utility" },
  { id: "rainwater-harvesting", name: "Rainwater Harvesting", icon: "CloudRain", category: "utility" },
];

// ============================================================================
// 24 MOCK PROPERTIES
// ============================================================================

export const mockProperties: Property[] = [
  // --- VISAKHAPATNAM (Base City) ---
  {
    id: "prop-001",
    slug: "luxury-sea-view-villa-rushikonda",
    title: "Luxury 4BHK Sea View Villa in Rushikonda",
    description: "Stunning sea-facing luxury villa perched on Rushikonda hilltop with panoramic Bay of Bengal views. Italian marble flooring, modular kitchen with Bosch appliances, private infinity pool, landscaped garden, and smart home automation. Walking distance to Rushikonda Beach. Perfect for discerning buyers who value exclusivity and nature.",
    propertyType: "villa",
    listingType: "sale",
    status: "featured",
    price: 85000000,
    pricePerSqft: 17000,
    area: 5000,
    carpetArea: 4200,
    builtUpArea: 4600,
    superBuiltUpArea: 5000,
    bedrooms: 4,
    bathrooms: 5,
    balconies: 3,
    floors: 2,
    totalFloors: 2,
    parking: 3,
    furnishing: "furnished",
    facing: "east",
    ageOfProperty: 1,
    isReadyToMove: true,
    location: {
      address: "Plot No. 42, Rushikonda Hilltop Road",
      locality: "Rushikonda",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      pincode: "530045",
      latitude: 17.7833,
      longitude: 83.3847,
    },
    images: propertyImages.luxury1,
    amenities: luxuryAmenities,
    features: [
      { label: "Construction", value: "RCC Frame Structure" },
      { label: "Flooring", value: "Italian Marble" },
      { label: "Water Supply", value: "Borewell + Municipal" },
      { label: "Kitchen", value: "Modular with Bosch Appliances" },
    ],
    reraId: "P01400006721",
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-002",
    ownerName: "Vikram Reddy",
    ownerPhone: "9876543210",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    ownerType: "owner",
    isOwnerVerified: true,
    viewCount: 1247,
    savedCount: 89,
    enquiryCount: 23,
    createdAt: "2025-11-15T10:30:00Z",
    updatedAt: "2026-06-20T14:00:00Z",
    publishedAt: "2025-11-20T08:00:00Z",
    vastuCompliant: true,
    petFriendly: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
    nearbySchools: ["Oakridge International School - 2km", "Delhi Public School - 3km"],
    nearbyHospitals: ["KIMS Hospital - 4km", "Care Hospital - 5km"],
    nearbyMetro: "Visakhapatnam Metro (upcoming) - 3km",
    nearbyAirport: "Visakhapatnam International Airport - 18km",
  },
  {
    id: "prop-002",
    slug: "3bhk-apartment-mvp-colony",
    title: "Spacious 3BHK in Gated Community, MVP Colony",
    description: "Well-maintained 3BHK apartment in a premium gated community at MVP Colony. Features include modular kitchen, wooden flooring in bedrooms, covered car parking, and access to clubhouse with swimming pool. Close to schools, hospitals, and shopping centres.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 9500000,
    pricePerSqft: 5278,
    area: 1800,
    carpetArea: 1450,
    builtUpArea: 1620,
    superBuiltUpArea: 1800,
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    totalFloors: 12,
    floorNumber: 7,
    parking: 1,
    furnishing: "semi-furnished",
    facing: "north-east",
    ageOfProperty: 3,
    isReadyToMove: true,
    location: {
      address: "Flat 702, Sai Enclave, Sector 6",
      locality: "MVP Colony",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      pincode: "530017",
      latitude: 17.7365,
      longitude: 83.3270,
    },
    images: propertyImages.apartment2,
    amenities: standardAmenities,
    features: [
      { label: "Construction", value: "RCC Frame" },
      { label: "Flooring", value: "Vitrified Tiles" },
      { label: "Water Supply", value: "Municipal" },
      { label: "Kitchen", value: "Modular" },
    ],
    reraId: "P01400003215",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-003",
    ownerName: "Sunita Sharma",
    ownerPhone: "9988776655",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    ownerType: "agent",
    isOwnerVerified: true,
    viewCount: 532,
    savedCount: 45,
    enquiryCount: 12,
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-06-28T11:00:00Z",
    publishedAt: "2026-03-12T08:00:00Z",
    vastuCompliant: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "municipal",
    nearbySchools: ["Timpany School - 1km"],
    nearbyHospitals: ["Seven Hills Hospital - 2km"],
  },
  {
    id: "prop-003",
    slug: "2bhk-rental-madhurawada",
    title: "2BHK Furnished Flat for Rent, Madhurawada",
    description: "Fully furnished 2BHK apartment available for rent in Madhurawada near IT SEZ. Brand new furniture, AC in all rooms, modular kitchen, high-speed internet ready. Ideal for IT professionals. 5 minutes from Lulu Mall and Rushikonda Beach.",
    propertyType: "apartment",
    listingType: "rent",
    status: "published",
    price: 22000,
    pricePerSqft: 0,
    maintenanceCharge: 3000,
    securityDeposit: 100000,
    area: 1100,
    carpetArea: 900,
    builtUpArea: 1000,
    superBuiltUpArea: 1100,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    totalFloors: 8,
    floorNumber: 4,
    parking: 1,
    furnishing: "furnished",
    facing: "south-east",
    ageOfProperty: 2,
    isReadyToMove: true,
    location: {
      address: "Flat 401, Green Heights, Madhurawada Junction",
      locality: "Madhurawada",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      pincode: "530048",
      latitude: 17.7869,
      longitude: 83.3714,
    },
    images: propertyImages.apartment1,
    amenities: standardAmenities.slice(0, 8),
    features: [
      { label: "Flooring", value: "Vitrified Tiles" },
      { label: "Water Supply", value: "Borewell" },
    ],
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-002",
    ownerName: "Vikram Reddy",
    ownerPhone: "9876543210",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    ownerType: "owner",
    isOwnerVerified: true,
    viewCount: 318,
    savedCount: 28,
    enquiryCount: 9,
    createdAt: "2026-05-01T10:00:00Z",
    updatedAt: "2026-07-01T10:00:00Z",
    publishedAt: "2026-05-03T08:00:00Z",
    powerBackup: true,
    waterSupply: "borewell",
  },
  {
    id: "prop-004",
    slug: "residential-plot-kommadi",
    title: "RERA Approved 200 Sq Yards Plot, Kommadi",
    description: "Prime residential plot at Kommadi near IT corridor. RERA approved layout with 40 ft road, underground drainage, street lights, and landscaped parks. Ideal investment opportunity near upcoming metro station.",
    propertyType: "residential-land",
    listingType: "sale",
    status: "published",
    price: 4500000,
    pricePerSqft: 2500,
    area: 1800,
    plotArea: 1800,
    bedrooms: 0,
    bathrooms: 0,
    balconies: 0,
    parking: 0,
    furnishing: "unfurnished",
    facing: "north",
    ageOfProperty: 0,
    isReadyToMove: true,
    location: {
      address: "Plot 156, Green Meadows Layout, Kommadi Road",
      locality: "Kommadi",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      pincode: "530048",
      latitude: 17.8012,
      longitude: 83.3651,
    },
    images: propertyImages.plot1,
    amenities: [],
    features: [
      { label: "Plot Type", value: "Residential" },
      { label: "Road Width", value: "40 ft" },
      { label: "Boundary Wall", value: "Yes" },
      { label: "Drainage", value: "Underground" },
    ],
    reraId: "P01400008432",
    isVerified: true,
    isFeatured: true,
    isPremium: false,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 412,
    savedCount: 56,
    enquiryCount: 18,
    createdAt: "2026-04-15T10:00:00Z",
    updatedAt: "2026-06-30T10:00:00Z",
    publishedAt: "2026-04-18T08:00:00Z",
  },
  // --- HYDERABAD ---
  {
    id: "prop-005",
    slug: "3bhk-premium-gachibowli",
    title: "Premium 3BHK in Gachibowli Financial District",
    description: "Brand new 3BHK apartment in the heart of Gachibowli Financial District. Floor-to-ceiling windows with stunning skyline views. Walking distance to major IT campuses including Microsoft, Amazon, and Google offices.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 18500000,
    pricePerSqft: 9250,
    area: 2000,
    carpetArea: 1650,
    builtUpArea: 1800,
    superBuiltUpArea: 2000,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    totalFloors: 25,
    floorNumber: 18,
    parking: 2,
    furnishing: "semi-furnished",
    facing: "west",
    ageOfProperty: 0,
    possessionDate: "2026-12-01",
    isReadyToMove: false,
    location: {
      address: "Tower B, Sky Towers, Financial District",
      locality: "Gachibowli",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500032",
      latitude: 17.4435,
      longitude: 78.3772,
    },
    images: propertyImages.apartment2,
    amenities: luxuryAmenities,
    features: [
      { label: "Construction", value: "RCC Shear Wall" },
      { label: "Flooring", value: "Italian Marble + Wooden" },
      { label: "Water Supply", value: "Borewell + Municipal" },
    ],
    reraId: "P02200005678",
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 892,
    savedCount: 134,
    enquiryCount: 42,
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-07-05T10:00:00Z",
    publishedAt: "2026-01-25T08:00:00Z",
    vastuCompliant: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
    nearbySchools: ["Oakridge International - 3km"],
    nearbyHospitals: ["Continental Hospitals - 2km"],
    nearbyMetro: "Raidurg Metro Station - 1.5km",
  },
  {
    id: "prop-006",
    slug: "luxury-villa-jubilee-hills",
    title: "Ultra-Luxury 5BHK Villa, Jubilee Hills Road No. 36",
    description: "Architectural masterpiece in the most prestigious address of Hyderabad. This 5BHK villa features imported materials, home theatre, temperature-controlled wine cellar, rooftop infinity pool, and private lift. Spread across 8000 sq ft of pure opulence.",
    propertyType: "villa",
    listingType: "sale",
    status: "featured",
    price: 250000000,
    pricePerSqft: 31250,
    area: 8000,
    carpetArea: 7000,
    builtUpArea: 7500,
    superBuiltUpArea: 8000,
    bedrooms: 5,
    bathrooms: 7,
    balconies: 4,
    floors: 3,
    totalFloors: 3,
    parking: 4,
    furnishing: "furnished",
    facing: "east",
    ageOfProperty: 2,
    isReadyToMove: true,
    location: {
      address: "Villa 12, Road No. 36, Jubilee Hills",
      locality: "Jubilee Hills",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500033",
      latitude: 17.4312,
      longitude: 78.4071,
    },
    images: propertyImages.luxury1,
    amenities: luxuryAmenities,
    features: [
      { label: "Construction", value: "Steel + RCC" },
      { label: "Flooring", value: "Imported Italian Marble" },
      { label: "Smart Home", value: "Full Automation" },
      { label: "Pool", value: "Rooftop Infinity Pool" },
    ],
    reraId: "P02200001234",
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-002",
    ownerName: "Vikram Reddy",
    ownerPhone: "9876543210",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    ownerType: "owner",
    isOwnerVerified: true,
    viewCount: 2341,
    savedCount: 203,
    enquiryCount: 15,
    createdAt: "2025-10-01T10:00:00Z",
    updatedAt: "2026-07-01T10:00:00Z",
    publishedAt: "2025-10-05T08:00:00Z",
    vastuCompliant: true,
    petFriendly: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
  },
  {
    id: "prop-007",
    slug: "commercial-office-hitech-city",
    title: "Plug & Play Office Space, Hitech City",
    description: "Ready-to-occupy commercial office space in prime Hitech City location. 100-seater capacity, server room, pantry, reception, and 24/7 access. Ideal for IT companies and startups. Excellent connectivity to Hitec City MMTS and Metro.",
    propertyType: "commercial-spaces",
    listingType: "rent",
    status: "published",
    price: 350000,
    pricePerSqft: 0,
    maintenanceCharge: 50000,
    securityDeposit: 2100000,
    area: 5000,
    carpetArea: 4200,
    bedrooms: 0,
    bathrooms: 4,
    balconies: 0,
    totalFloors: 15,
    floorNumber: 9,
    parking: 10,
    furnishing: "furnished",
    facing: "north",
    ageOfProperty: 5,
    isReadyToMove: true,
    location: {
      address: "Floor 9, Cyber Pearl, Hitech City Main Road",
      locality: "Hitech City",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500081",
      latitude: 17.4486,
      longitude: 78.3908,
    },
    images: propertyImages.commercial1,
    amenities: [
      { id: "power-backup", name: "100% Power Backup", icon: "Zap", category: "utility" },
      { id: "lift", name: "High-Speed Lifts", icon: "ArrowUpDown", category: "basic" },
      { id: "gated-security", name: "24/7 Security", icon: "Shield", category: "safety" },
      { id: "covered-parking", name: "Basement Parking", icon: "Car", category: "parking" },
      { id: "cctv", name: "CCTV", icon: "Camera", category: "safety" },
    ],
    features: [
      { label: "Type", value: "Fully Furnished Office" },
      { label: "Workstations", value: "100" },
      { label: "AC", value: "Central" },
      { label: "Internet", value: "Fiber - 1 Gbps" },
    ],
    isVerified: true,
    isFeatured: false,
    isPremium: true,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 456,
    savedCount: 34,
    enquiryCount: 21,
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-06-25T10:00:00Z",
    publishedAt: "2026-02-18T08:00:00Z",
    powerBackup: true,
  },
  {
    id: "prop-008",
    slug: "2bhk-rental-kondapur",
    title: "Modern 2BHK for Rent near Botanical Garden, Kondapur",
    description: "Bright and airy 2BHK flat in a well-maintained society near Botanical Garden. Semi-furnished with modular kitchen. Walking distance to D-Mart, Apollo Pharmacy, and multiple restaurants. Ideal for small families and working couples.",
    propertyType: "apartment",
    listingType: "rent",
    status: "published",
    price: 28000,
    pricePerSqft: 0,
    maintenanceCharge: 3500,
    securityDeposit: 140000,
    area: 1200,
    carpetArea: 950,
    builtUpArea: 1080,
    superBuiltUpArea: 1200,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    totalFloors: 14,
    floorNumber: 6,
    parking: 1,
    furnishing: "semi-furnished",
    facing: "north-east",
    ageOfProperty: 4,
    isReadyToMove: true,
    location: {
      address: "Flat 604, Lakshmi Heights, Botanical Garden Road",
      locality: "Kondapur",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500084",
      latitude: 17.4601,
      longitude: 78.3576,
    },
    images: propertyImages.apartment1,
    amenities: standardAmenities.slice(0, 8),
    features: [
      { label: "Flooring", value: "Vitrified Tiles" },
      { label: "Kitchen", value: "Modular" },
    ],
    reraId: "P02200009871",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-003",
    ownerName: "Sunita Sharma",
    ownerPhone: "9988776655",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    ownerType: "agent",
    isOwnerVerified: true,
    viewCount: 287,
    savedCount: 22,
    enquiryCount: 8,
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-07-05T10:00:00Z",
    publishedAt: "2026-06-03T08:00:00Z",
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
  },
  // --- BENGALURU ---
  {
    id: "prop-009",
    slug: "4bhk-penthouse-koramangala",
    title: "Luxurious 4BHK Penthouse, Koramangala",
    description: "Stunning duplex penthouse with panoramic city views in the heart of Koramangala. Features a private terrace with jacuzzi, home office, modular kitchen with imported fittings, and floor-to-ceiling windows. Minutes from Koramangala's vibrant dining and retail scene.",
    propertyType: "apartment",
    listingType: "sale",
    status: "featured",
    price: 45000000,
    pricePerSqft: 15000,
    area: 3000,
    carpetArea: 2600,
    builtUpArea: 2800,
    superBuiltUpArea: 3000,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    totalFloors: 20,
    floorNumber: 20,
    parking: 2,
    furnishing: "furnished",
    facing: "south-east",
    ageOfProperty: 1,
    isReadyToMove: true,
    location: {
      address: "Penthouse 2001, The Summit, 80 Feet Road",
      locality: "Koramangala",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560034",
      latitude: 12.9352,
      longitude: 77.6245,
    },
    images: propertyImages.luxury1,
    amenities: luxuryAmenities,
    features: [
      { label: "Type", value: "Duplex Penthouse" },
      { label: "Flooring", value: "Imported Marble + Hardwood" },
      { label: "Terrace", value: "Private with Jacuzzi" },
    ],
    reraId: "PRM/KA/RERA/1251/308/PR/190516/002347",
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-002",
    ownerName: "Vikram Reddy",
    ownerPhone: "9876543210",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    ownerType: "owner",
    isOwnerVerified: true,
    viewCount: 1123,
    savedCount: 167,
    enquiryCount: 31,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-07-08T10:00:00Z",
    publishedAt: "2026-02-05T08:00:00Z",
    vastuCompliant: true,
    petFriendly: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
  },
  {
    id: "prop-010",
    slug: "pg-accommodation-whitefield",
    title: "Premium Boys PG near ITPB, Whitefield",
    description: "Fully furnished premium PG accommodation near ITPB Whitefield. AC rooms, attached bathroom, daily housekeeping, meals included, high-speed Wi-Fi, and 24/7 security. 10 minutes walk to ITPB gate. Separate PGs for boys and girls available.",
    propertyType: "pg-coliving",
    listingType: "pg",
    status: "published",
    price: 12000,
    pricePerSqft: 0,
    area: 150,
    bedrooms: 1,
    bathrooms: 1,
    balconies: 0,
    totalFloors: 4,
    floorNumber: 2,
    parking: 0,
    furnishing: "furnished",
    facing: "north",
    ageOfProperty: 3,
    isReadyToMove: true,
    location: {
      address: "23, ITPB Main Road, Near Phoenix Marketcity",
      locality: "Whitefield",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560066",
      latitude: 12.9698,
      longitude: 77.7500,
    },
    images: propertyImages.pg1,
    amenities: [
      { id: "power-backup", name: "Power Backup", icon: "Zap", category: "utility" },
      { id: "water-supply", name: "24x7 Water", icon: "Droplets", category: "utility" },
      { id: "cctv", name: "CCTV", icon: "Camera", category: "safety" },
      { id: "gated-security", name: "Security", icon: "Shield", category: "safety" },
    ],
    features: [
      { label: "Meals", value: "3 Meals + Snacks" },
      { label: "Laundry", value: "Weekly" },
      { label: "Wi-Fi", value: "100 Mbps" },
      { label: "Room Type", value: "Single Occupancy" },
    ],
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-004",
    ownerName: "Rahul Gupta",
    ownerPhone: "9900112233",
    ownerType: "owner",
    isOwnerVerified: false,
    viewCount: 645,
    savedCount: 89,
    enquiryCount: 34,
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-07-09T10:00:00Z",
    publishedAt: "2026-04-03T08:00:00Z",
    powerBackup: true,
  },
  {
    id: "prop-011",
    slug: "independent-house-hsr-layout",
    title: "Independent 3BHK House with Garden, HSR Layout",
    description: "Charming independent house in HSR Layout with a private garden and terrace. Vastu-compliant, east-facing, quiet residential area. Close to Agara Lake, cafes, and tech parks. Ideal for families seeking space and privacy.",
    propertyType: "independent-house",
    listingType: "sale",
    status: "published",
    price: 28000000,
    pricePerSqft: 11200,
    area: 2500,
    carpetArea: 2100,
    builtUpArea: 2300,
    superBuiltUpArea: 2500,
    plotArea: 3200,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floors: 2,
    totalFloors: 2,
    parking: 2,
    furnishing: "semi-furnished",
    facing: "east",
    ageOfProperty: 5,
    isReadyToMove: true,
    location: {
      address: "23, 14th Cross, Sector 1, HSR Layout",
      locality: "HSR Layout",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560102",
      latitude: 12.9116,
      longitude: 77.6389,
    },
    images: propertyImages.villa1,
    amenities: standardAmenities.slice(0, 6),
    features: [
      { label: "Plot Area", value: "3,200 sq.ft" },
      { label: "Garden", value: "Private Landscaped" },
      { label: "Terrace", value: "Open Terrace" },
    ],
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-003",
    ownerName: "Sunita Sharma",
    ownerPhone: "9988776655",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    ownerType: "agent",
    isOwnerVerified: true,
    viewCount: 389,
    savedCount: 67,
    enquiryCount: 14,
    createdAt: "2026-05-10T10:00:00Z",
    updatedAt: "2026-07-05T10:00:00Z",
    publishedAt: "2026-05-12T08:00:00Z",
    vastuCompliant: true,
    gatedSecurity: false,
    powerBackup: true,
    waterSupply: "borewell",
  },
  // --- CHENNAI ---
  {
    id: "prop-012",
    slug: "2bhk-apartment-omr-chennai",
    title: "New 2BHK Apartment on OMR IT Expressway",
    description: "Brand new 2BHK apartment in a gated community on OMR. Close to TCS, Infosys, and Cognizant campuses. Modern amenities including rooftop infinity pool, co-working space, and EV charging stations.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 7800000,
    pricePerSqft: 6500,
    area: 1200,
    carpetArea: 980,
    builtUpArea: 1080,
    superBuiltUpArea: 1200,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    totalFloors: 18,
    floorNumber: 12,
    parking: 1,
    furnishing: "unfurnished",
    facing: "south",
    ageOfProperty: 0,
    possessionDate: "2027-03-01",
    isReadyToMove: false,
    location: {
      address: "Block C, Urban Rise, Sholinganallur",
      locality: "OMR",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600119",
      latitude: 12.9010,
      longitude: 80.2279,
    },
    images: propertyImages.apartment1,
    amenities: luxuryAmenities.slice(0, 10),
    features: [
      { label: "Construction Status", value: "Under Construction" },
      { label: "Possession", value: "March 2027" },
    ],
    reraId: "TN/01/Building/0123/2026",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 234,
    savedCount: 41,
    enquiryCount: 11,
    createdAt: "2026-06-15T10:00:00Z",
    updatedAt: "2026-07-08T10:00:00Z",
    publishedAt: "2026-06-18T08:00:00Z",
    powerBackup: true,
    waterSupply: "both",
  },
  {
    id: "prop-013",
    slug: "luxury-ecr-villa-chennai",
    title: "Beach-Facing Luxury Villa on ECR, Chennai",
    description: "Exquisite beach-facing villa on East Coast Road with direct beach access. Contemporary architecture with open-plan living, private pool, outdoor BBQ area, and rooftop lounge. Perfect weekend getaway or permanent residence.",
    propertyType: "villa",
    listingType: "sale",
    status: "featured",
    price: 120000000,
    pricePerSqft: 20000,
    area: 6000,
    carpetArea: 5200,
    builtUpArea: 5600,
    superBuiltUpArea: 6000,
    plotArea: 10000,
    bedrooms: 4,
    bathrooms: 5,
    balconies: 3,
    floors: 2,
    totalFloors: 2,
    parking: 3,
    furnishing: "furnished",
    facing: "east",
    ageOfProperty: 1,
    isReadyToMove: true,
    location: {
      address: "Seashore Villa 8, ECR, Thiruvanmiyur",
      locality: "ECR",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600041",
      latitude: 12.9855,
      longitude: 80.2590,
    },
    images: propertyImages.luxury1,
    amenities: luxuryAmenities,
    features: [
      { label: "Beach Access", value: "Direct Private" },
      { label: "Pool", value: "Private Infinity Pool" },
      { label: "Smart Home", value: "Full Automation" },
    ],
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-002",
    ownerName: "Vikram Reddy",
    ownerPhone: "9876543210",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    ownerType: "owner",
    isOwnerVerified: true,
    viewCount: 1567,
    savedCount: 145,
    enquiryCount: 8,
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-07-01T10:00:00Z",
    publishedAt: "2026-01-15T08:00:00Z",
    vastuCompliant: true,
    petFriendly: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
  },
  // --- MUMBAI ---
  {
    id: "prop-014",
    slug: "3bhk-sea-facing-bandra",
    title: "3BHK Sea-Facing Apartment, Bandra West",
    description: "Rare sea-facing 3BHK in the most coveted address of Bandra West. Unobstructed Arabian Sea views from every room. High ceilings, imported fixtures, Italian marble throughout. Walking distance to Bandstand Promenade and Linking Road.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 75000000,
    pricePerSqft: 50000,
    area: 1500,
    carpetArea: 1200,
    builtUpArea: 1350,
    superBuiltUpArea: 1500,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    totalFloors: 30,
    floorNumber: 22,
    parking: 2,
    furnishing: "furnished",
    facing: "west",
    ageOfProperty: 3,
    isReadyToMove: true,
    location: {
      address: "2202, The Horizon, Carter Road, Bandra West",
      locality: "Bandra",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400050",
      latitude: 19.0596,
      longitude: 72.8295,
    },
    images: propertyImages.apartment2,
    amenities: luxuryAmenities,
    features: [
      { label: "View", value: "Unobstructed Sea View" },
      { label: "Ceiling Height", value: "12 ft" },
      { label: "Flooring", value: "Italian Calacatta Marble" },
    ],
    reraId: "P51800012345",
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-003",
    ownerName: "Sunita Sharma",
    ownerPhone: "9988776655",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    ownerType: "agent",
    isOwnerVerified: true,
    viewCount: 3456,
    savedCount: 312,
    enquiryCount: 56,
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2026-07-10T10:00:00Z",
    publishedAt: "2025-12-05T08:00:00Z",
    vastuCompliant: false,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "municipal",
  },
  {
    id: "prop-015",
    slug: "1bhk-andheri-rental",
    title: "1BHK Compact Flat for Rent, Andheri East",
    description: "Ideal 1BHK for working professionals near Andheri Metro Station. Fully furnished with AC, washing machine, and modular kitchen. Walking distance to WEH and multiple IT parks. No brokerage for direct tenant.",
    propertyType: "apartment",
    listingType: "rent",
    status: "published",
    price: 35000,
    pricePerSqft: 0,
    maintenanceCharge: 4500,
    securityDeposit: 105000,
    area: 550,
    carpetArea: 430,
    builtUpArea: 500,
    superBuiltUpArea: 550,
    bedrooms: 1,
    bathrooms: 1,
    balconies: 0,
    totalFloors: 20,
    floorNumber: 14,
    parking: 0,
    furnishing: "furnished",
    facing: "north",
    ageOfProperty: 6,
    isReadyToMove: true,
    location: {
      address: "1401, Ruby Apartments, MIDC Road, Andheri East",
      locality: "Andheri",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400093",
      latitude: 19.1136,
      longitude: 72.8697,
    },
    images: propertyImages.apartment1,
    amenities: standardAmenities.slice(0, 5),
    features: [
      { label: "Furnishing", value: "Fully Furnished" },
      { label: "AC", value: "1 Split AC" },
    ],
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-004",
    ownerName: "Rahul Gupta",
    ownerPhone: "9900112233",
    ownerType: "owner",
    isOwnerVerified: false,
    viewCount: 876,
    savedCount: 67,
    enquiryCount: 23,
    createdAt: "2026-06-20T10:00:00Z",
    updatedAt: "2026-07-09T10:00:00Z",
    publishedAt: "2026-06-22T08:00:00Z",
    powerBackup: true,
    waterSupply: "municipal",
    nearbyMetro: "Andheri Metro Station - 500m",
  },
  // --- DELHI NCR ---
  {
    id: "prop-016",
    slug: "4bhk-penthouse-gurugram",
    title: "Sky Penthouse 4BHK, Golf Course Road, Gurugram",
    description: "Ultra-premium penthouse on Golf Course Road with breathtaking views of the Aravallis and the golf course. Private elevator, home theatre, wine room, and wrap-around terrace. Concierge services included.",
    propertyType: "apartment",
    listingType: "sale",
    status: "featured",
    price: 150000000,
    pricePerSqft: 37500,
    area: 4000,
    carpetArea: 3400,
    builtUpArea: 3700,
    superBuiltUpArea: 4000,
    bedrooms: 4,
    bathrooms: 5,
    balconies: 3,
    totalFloors: 40,
    floorNumber: 40,
    parking: 3,
    furnishing: "furnished",
    facing: "south-west",
    ageOfProperty: 2,
    isReadyToMove: true,
    location: {
      address: "Penthouse, Tower A, DLF Camellias, Golf Course Road",
      locality: "Gurugram",
      city: "Delhi NCR",
      state: "Haryana",
      pincode: "122002",
      latitude: 28.4595,
      longitude: 77.0266,
    },
    images: propertyImages.luxury1,
    amenities: luxuryAmenities,
    features: [
      { label: "Elevator", value: "Private" },
      { label: "View", value: "Golf Course + Aravallis" },
      { label: "Concierge", value: "24/7" },
    ],
    reraId: "GGM/REP/RERA-286/2023",
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-003",
    ownerName: "Sunita Sharma",
    ownerPhone: "9988776655",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    ownerType: "agent",
    isOwnerVerified: true,
    viewCount: 1890,
    savedCount: 234,
    enquiryCount: 18,
    createdAt: "2025-11-01T10:00:00Z",
    updatedAt: "2026-07-05T10:00:00Z",
    publishedAt: "2025-11-05T08:00:00Z",
    vastuCompliant: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
  },
  {
    id: "prop-017",
    slug: "3bhk-noida-sector-150",
    title: "Affordable 3BHK in Noida Sector 150",
    description: "Value-for-money 3BHK apartment in upcoming Sector 150 with excellent connectivity to Noida Expressway. Project features 70% open green area, Olympic-size pool, and international school within the township.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 8500000,
    pricePerSqft: 4722,
    area: 1800,
    carpetArea: 1450,
    builtUpArea: 1620,
    superBuiltUpArea: 1800,
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    totalFloors: 22,
    floorNumber: 10,
    parking: 1,
    furnishing: "unfurnished",
    facing: "north-east",
    ageOfProperty: 0,
    possessionDate: "2027-06-01",
    isReadyToMove: false,
    location: {
      address: "Tower 5, Ace Parkway, Sector 150",
      locality: "Noida",
      city: "Delhi NCR",
      state: "Uttar Pradesh",
      pincode: "201310",
      latitude: 28.5672,
      longitude: 77.3910,
    },
    images: propertyImages.apartment2,
    amenities: luxuryAmenities.slice(0, 12),
    features: [
      { label: "Green Area", value: "70%" },
      { label: "Possession", value: "June 2027" },
    ],
    reraId: "UPRERAPRJ17324",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 567,
    savedCount: 78,
    enquiryCount: 32,
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-07-08T10:00:00Z",
    publishedAt: "2026-05-22T08:00:00Z",
    powerBackup: true,
    waterSupply: "both",
  },
  {
    id: "prop-018",
    slug: "farmhouse-chattarpur",
    title: "Luxury Farmhouse with Orchard, Chattarpur",
    description: "Sprawling 1-acre farmhouse in Chattarpur with mango and litchi orchards, private pool, outdoor cinema, stables, and guest cottage. Perfect for weekend retreats or corporate off-sites.",
    propertyType: "farmhouse",
    listingType: "sale",
    status: "published",
    price: 180000000,
    pricePerSqft: 4132,
    area: 43560,
    plotArea: 43560,
    bedrooms: 5,
    bathrooms: 6,
    balconies: 4,
    floors: 2,
    totalFloors: 2,
    parking: 8,
    furnishing: "furnished",
    facing: "east",
    ageOfProperty: 8,
    isReadyToMove: true,
    location: {
      address: "Farm No. 23, Chattarpur Enclave, Phase 2",
      locality: "Vasant Kunj",
      city: "Delhi NCR",
      state: "Delhi",
      pincode: "110074",
      latitude: 28.5068,
      longitude: 77.1581,
    },
    images: propertyImages.farmhouse1,
    amenities: luxuryAmenities,
    features: [
      { label: "Land Area", value: "1 Acre" },
      { label: "Orchard", value: "Mango + Litchi" },
      { label: "Pool", value: "Heated" },
      { label: "Guest Cottage", value: "2BHK" },
    ],
    isVerified: true,
    isFeatured: true,
    isPremium: true,
    ownerId: "user-002",
    ownerName: "Vikram Reddy",
    ownerPhone: "9876543210",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    ownerType: "owner",
    isOwnerVerified: true,
    viewCount: 934,
    savedCount: 112,
    enquiryCount: 7,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-07-01T10:00:00Z",
    publishedAt: "2026-03-05T08:00:00Z",
    vastuCompliant: true,
    petFriendly: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "borewell",
  },
  // Additional properties for coverage
  {
    id: "prop-019",
    slug: "budget-2bhk-gajuwaka",
    title: "Affordable 2BHK Apartment, Gajuwaka",
    description: "Budget-friendly 2BHK apartment in a growing locality near Vizag Steel Plant. Good ventilation, covered parking, and proximity to schools. Ideal for first-time buyers.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 3200000,
    pricePerSqft: 3200,
    area: 1000,
    carpetArea: 800,
    builtUpArea: 900,
    superBuiltUpArea: 1000,
    bedrooms: 2,
    bathrooms: 1,
    balconies: 1,
    totalFloors: 5,
    floorNumber: 3,
    parking: 1,
    furnishing: "unfurnished",
    facing: "south",
    ageOfProperty: 2,
    isReadyToMove: true,
    location: {
      address: "Flat 301, Sri Sai Residency, Old Post Office Road",
      locality: "Gajuwaka",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      pincode: "530026",
      latitude: 17.7010,
      longitude: 83.2147,
    },
    images: propertyImages.apartment1,
    amenities: standardAmenities.slice(0, 4),
    features: [
      { label: "Flooring", value: "Granite" },
      { label: "Water Supply", value: "Municipal" },
    ],
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-004",
    ownerName: "Rahul Gupta",
    ownerPhone: "9900112233",
    ownerType: "owner",
    isOwnerVerified: false,
    viewCount: 189,
    savedCount: 23,
    enquiryCount: 6,
    createdAt: "2026-06-10T10:00:00Z",
    updatedAt: "2026-07-05T10:00:00Z",
    publishedAt: "2026-06-12T08:00:00Z",
    waterSupply: "municipal",
  },
  {
    id: "prop-020",
    slug: "commercial-shop-kukatpally",
    title: "Ready Commercial Shop, KPHB Colony, Kukatpally",
    description: "Ground floor commercial shop in a high-footfall area of KPHB Colony. 30ft frontage, suitable for retail, banking, or showroom. High rental yield area near Kukatpally Metro.",
    propertyType: "commercial-spaces",
    listingType: "sale",
    status: "published",
    price: 15000000,
    pricePerSqft: 15000,
    area: 1000,
    carpetArea: 850,
    builtUpArea: 950,
    superBuiltUpArea: 1000,
    bedrooms: 0,
    bathrooms: 1,
    balconies: 0,
    totalFloors: 6,
    floorNumber: 0,
    parking: 0,
    furnishing: "unfurnished",
    facing: "north",
    ageOfProperty: 4,
    isReadyToMove: true,
    location: {
      address: "Shop G-12, Sai Commercial Complex, KPHB Phase 1",
      locality: "Kukatpally",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500072",
      latitude: 17.4948,
      longitude: 78.3996,
    },
    images: propertyImages.commercial1,
    amenities: [
      { id: "power-backup", name: "Power Backup", icon: "Zap", category: "utility" },
      { id: "covered-parking", name: "Visitor Parking", icon: "Car", category: "parking" },
    ],
    features: [
      { label: "Frontage", value: "30 ft" },
      { label: "Floor", value: "Ground" },
    ],
    reraId: "P02200006543",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 312,
    savedCount: 28,
    enquiryCount: 9,
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-07-02T10:00:00Z",
    publishedAt: "2026-04-22T08:00:00Z",
    powerBackup: true,
  },
  {
    id: "prop-021",
    slug: "1bhk-studio-electronic-city",
    title: "Smart 1BHK Studio, Electronic City Phase 1",
    description: "Compact and efficient 1BHK studio apartment near Electronic City. Modern design with smart storage solutions. Close to Infosys, Wipro, and TCS campuses. Metro connectivity upcoming.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 4200000,
    pricePerSqft: 6000,
    area: 700,
    carpetArea: 560,
    builtUpArea: 630,
    superBuiltUpArea: 700,
    bedrooms: 1,
    bathrooms: 1,
    balconies: 1,
    totalFloors: 14,
    floorNumber: 8,
    parking: 1,
    furnishing: "unfurnished",
    facing: "west",
    ageOfProperty: 1,
    isReadyToMove: true,
    location: {
      address: "Unit 804, Prestige Tech Park Residences, Neeladri Road",
      locality: "Electronic City",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560100",
      latitude: 12.8456,
      longitude: 77.6719,
    },
    images: propertyImages.apartment1,
    amenities: standardAmenities.slice(0, 8),
    features: [
      { label: "Configuration", value: "Studio with Utility" },
    ],
    reraId: "PRM/KA/RERA/1251/446/PR/200718/003456",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 456,
    savedCount: 67,
    enquiryCount: 19,
    createdAt: "2026-05-15T10:00:00Z",
    updatedAt: "2026-07-06T10:00:00Z",
    publishedAt: "2026-05-18T08:00:00Z",
    powerBackup: true,
    waterSupply: "borewell",
  },
  {
    id: "prop-022",
    slug: "3bhk-anna-nagar-chennai",
    title: "Premium 3BHK in Anna Nagar, Chennai",
    description: "Well-designed 3BHK in a reputed builder's project in Anna Nagar. Close to Anna Nagar Tower Park, schools, and hospitals. Excellent road connectivity and metro access.",
    propertyType: "apartment",
    listingType: "sale",
    status: "published",
    price: 14500000,
    pricePerSqft: 8056,
    area: 1800,
    carpetArea: 1450,
    builtUpArea: 1620,
    superBuiltUpArea: 1800,
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    totalFloors: 16,
    floorNumber: 11,
    parking: 1,
    furnishing: "semi-furnished",
    facing: "east",
    ageOfProperty: 3,
    isReadyToMove: true,
    location: {
      address: "1102, Green Enclave, 3rd Avenue, Anna Nagar",
      locality: "Anna Nagar",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600040",
      latitude: 13.0878,
      longitude: 80.2085,
    },
    images: propertyImages.apartment2,
    amenities: standardAmenities,
    features: [
      { label: "Flooring", value: "Vitrified + Wooden" },
      { label: "Kitchen", value: "Modular with Chimney" },
    ],
    reraId: "TN/01/Building/0089/2024",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-003",
    ownerName: "Sunita Sharma",
    ownerPhone: "9988776655",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    ownerType: "agent",
    isOwnerVerified: true,
    viewCount: 345,
    savedCount: 52,
    enquiryCount: 14,
    createdAt: "2026-04-10T10:00:00Z",
    updatedAt: "2026-07-03T10:00:00Z",
    publishedAt: "2026-04-12T08:00:00Z",
    vastuCompliant: true,
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "both",
  },
  {
    id: "prop-023",
    slug: "plot-sarjapur-road-bengaluru",
    title: "Premium Residential Plot, Sarjapur Road",
    description: "BMRDA approved residential plot in a gated plotted development on Sarjapur Road. Well-connected to ORR, Wipro Corporate Office, and multiple schools. Ready for construction with all approvals in place.",
    propertyType: "residential-land",
    listingType: "sale",
    status: "published",
    price: 12000000,
    pricePerSqft: 5000,
    area: 2400,
    plotArea: 2400,
    bedrooms: 0,
    bathrooms: 0,
    balconies: 0,
    parking: 0,
    furnishing: "unfurnished",
    facing: "north-east",
    ageOfProperty: 0,
    isReadyToMove: true,
    location: {
      address: "Plot 78, Prestige Ozone, Sarjapur Road",
      locality: "Sarjapur Road",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "562125",
      latitude: 12.8610,
      longitude: 77.7800,
    },
    images: propertyImages.plot1,
    amenities: [],
    features: [
      { label: "Approval", value: "BMRDA Approved" },
      { label: "Road Width", value: "60 ft Main + 40 ft Internal" },
      { label: "Gated", value: "Yes, 24/7 Security" },
    ],
    reraId: "PRM/KA/RERA/1251/303/PR/190410/002111",
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    ownerPhone: "9112233445",
    ownerType: "developer",
    isOwnerVerified: true,
    viewCount: 278,
    savedCount: 45,
    enquiryCount: 12,
    createdAt: "2026-05-25T10:00:00Z",
    updatedAt: "2026-07-07T10:00:00Z",
    publishedAt: "2026-05-28T08:00:00Z",
    gatedSecurity: true,
  },
  {
    id: "prop-024",
    slug: "rental-2bhk-powai-mumbai",
    title: "Lake View 2BHK for Rent, Powai, Mumbai",
    description: "Beautiful 2BHK apartment overlooking Powai Lake. Semi-furnished with vitrified tiles, modular kitchen, and covered parking. Walking distance to IIT Bombay campus, Hiranandani Gardens, and multiple restaurants.",
    propertyType: "apartment",
    listingType: "rent",
    status: "published",
    price: 55000,
    pricePerSqft: 0,
    maintenanceCharge: 6000,
    securityDeposit: 165000,
    area: 1100,
    carpetArea: 880,
    builtUpArea: 990,
    superBuiltUpArea: 1100,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    totalFloors: 25,
    floorNumber: 15,
    parking: 1,
    furnishing: "semi-furnished",
    facing: "north-west",
    ageOfProperty: 8,
    isReadyToMove: true,
    location: {
      address: "1502, Lake Vista, Hiranandani Gardens, Powai",
      locality: "Powai",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400076",
      latitude: 19.1197,
      longitude: 72.9090,
    },
    images: propertyImages.apartment2,
    amenities: standardAmenities,
    features: [
      { label: "View", value: "Powai Lake View" },
      { label: "Flooring", value: "Vitrified Tiles" },
    ],
    isVerified: true,
    isFeatured: false,
    isPremium: false,
    ownerId: "user-004",
    ownerName: "Rahul Gupta",
    ownerPhone: "9900112233",
    ownerType: "owner",
    isOwnerVerified: false,
    viewCount: 567,
    savedCount: 45,
    enquiryCount: 18,
    createdAt: "2026-06-05T10:00:00Z",
    updatedAt: "2026-07-09T10:00:00Z",
    publishedAt: "2026-06-07T08:00:00Z",
    gatedSecurity: true,
    powerBackup: true,
    waterSupply: "municipal",
    nearbySchools: ["Hiranandani Foundation School - 500m"],
    nearbyHospitals: ["Fortis Hospital - 1km"],
  },
];

// ============================================================================
// MOCK USERS
// ============================================================================

export const mockUsers: UserProfile[] = [
  {
    id: "user-001",
    email: "admin@road.in",
    phone: "9000000001",
    firstName: "Aasrith",
    lastName: "Admin",
    fullName: "Aasrith Admin",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
    role: "super-admin",
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdVerified: true,
    profileCompletionPercent: 100,
    bio: "Platform administrator",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    joinedAt: "2025-01-01T00:00:00Z",
    lastActiveAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "user-002",
    email: "vikram.reddy@gmail.com",
    phone: "9876543210",
    firstName: "Vikram",
    lastName: "Reddy",
    fullName: "Vikram Reddy",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    role: "owner",
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdVerified: true,
    profileCompletionPercent: 100,
    bio: "Property investor and owner with 15+ years of experience in Vizag and Hyderabad real estate market.",
    company: "Reddy Properties",
    reraLicense: "AP/RERA/AGENT/2023/001234",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    totalListings: 8,
    totalSoldRented: 23,
    rating: 4.8,
    reviewCount: 45,
    joinedAt: "2025-03-15T00:00:00Z",
    lastActiveAt: "2026-07-10T09:30:00Z",
  },
  {
    id: "user-003",
    email: "sunita.sharma@realty.com",
    phone: "9988776655",
    firstName: "Sunita",
    lastName: "Sharma",
    fullName: "Sunita Sharma",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    role: "agent",
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdVerified: true,
    profileCompletionPercent: 95,
    bio: "Top-performing real estate agent specializing in luxury properties across South India. Certified by RERA.",
    company: "Sharma Realty",
    companyLogo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&q=80",
    reraLicense: "KA/RERA/AGENT/2024/005678",
    city: "Bengaluru",
    state: "Karnataka",
    totalListings: 15,
    totalSoldRented: 67,
    rating: 4.9,
    reviewCount: 89,
    joinedAt: "2025-06-01T00:00:00Z",
    lastActiveAt: "2026-07-10T08:00:00Z",
  },
  {
    id: "user-004",
    email: "rahul.gupta@gmail.com",
    phone: "9900112233",
    firstName: "Rahul",
    lastName: "Gupta",
    fullName: "Rahul Gupta",
    role: "owner",
    isVerified: false,
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdVerified: false,
    profileCompletionPercent: 60,
    bio: "First-time property lister.",
    city: "Mumbai",
    state: "Maharashtra",
    totalListings: 3,
    totalSoldRented: 0,
    joinedAt: "2026-04-01T00:00:00Z",
    lastActiveAt: "2026-07-09T15:00:00Z",
  },
  {
    id: "user-005",
    email: "info@srinivasdev.com",
    phone: "9112233445",
    firstName: "Srinivas",
    lastName: "Developers",
    fullName: "Srinivas Developers",
    avatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&q=80",
    role: "developer",
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
    isIdVerified: true,
    profileCompletionPercent: 100,
    bio: "Leading real estate developer in South India with 20+ years of experience and 50+ completed projects.",
    company: "Srinivas Developers Pvt. Ltd.",
    companyLogo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&q=80",
    reraLicense: "AP/RERA/DEV/2020/000456",
    city: "Hyderabad",
    state: "Telangana",
    totalListings: 25,
    totalSoldRented: 150,
    rating: 4.7,
    reviewCount: 120,
    joinedAt: "2025-01-15T00:00:00Z",
    lastActiveAt: "2026-07-10T11:00:00Z",
  },
];

// ============================================================================
// MOCK NOTIFICATIONS
// ============================================================================

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    userId: "user-002",
    type: "lead",
    title: "New Enquiry Received",
    message: "Priya Mehta is interested in your Rushikonda villa listing. Respond within 24 hours for best results.",
    link: "/dashboard/listings/leads",
    isRead: false,
    createdAt: "2026-07-10T08:30:00Z",
  },
  {
    id: "notif-002",
    userId: "user-002",
    type: "price-drop",
    title: "Price Drop Alert",
    message: "A 3BHK in MVP Colony you saved has dropped by ₹5,00,000. Check it out!",
    link: "/properties/3bhk-apartment-mvp-colony",
    isRead: false,
    createdAt: "2026-07-09T14:00:00Z",
  },
  {
    id: "notif-003",
    userId: "user-002",
    type: "verification",
    title: "Verification Approved",
    message: "Your identity verification has been approved. You now have a verified badge on your profile.",
    link: "/dashboard/settings/profile",
    isRead: true,
    createdAt: "2026-07-08T10:00:00Z",
  },
  {
    id: "notif-004",
    userId: "user-002",
    type: "system",
    title: "Listing Expiring Soon",
    message: "Your listing 'Luxury Sea View Villa, Rushikonda' will expire in 7 days. Renew now to keep it visible.",
    link: "/dashboard/listings",
    isRead: true,
    createdAt: "2026-07-07T09:00:00Z",
  },
  {
    id: "notif-005",
    userId: "user-002",
    type: "new-match",
    title: "New Property Match",
    message: "3 new properties match your saved search 'Villas in Rushikonda under ₹1Cr'.",
    link: "/dashboard/searches",
    isRead: false,
    createdAt: "2026-07-10T06:00:00Z",
  },
];

// ============================================================================
// MOCK MESSAGES & CHATS
// ============================================================================

export const mockChats: Chat[] = [
  {
    id: "chat-001",
    participants: [
      { userId: "user-002", name: "Vikram Reddy", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80", role: "owner", isOnline: true },
      { userId: "user-006", name: "Priya Mehta", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80", role: "buyer", isOnline: false },
    ],
    propertyId: "prop-001",
    propertyTitle: "Luxury 4BHK Sea View Villa in Rushikonda",
    unreadCount: 2,
    createdAt: "2026-07-08T10:00:00Z",
    updatedAt: "2026-07-10T09:15:00Z",
    lastMessage: {
      id: "msg-005",
      chatId: "chat-001",
      senderId: "user-006",
      senderName: "Priya Mehta",
      senderAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
      content: "Can we schedule a visit this weekend? Saturday morning works best for me.",
      type: "text",
      isRead: false,
      sentAt: "2026-07-10T09:15:00Z",
    },
  },
  {
    id: "chat-002",
    participants: [
      { userId: "user-002", name: "Vikram Reddy", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80", role: "owner", isOnline: true },
      { userId: "user-007", name: "Amit Kumar", role: "buyer", isOnline: true },
    ],
    propertyId: "prop-003",
    propertyTitle: "2BHK Furnished Flat for Rent, Madhurawada",
    unreadCount: 0,
    createdAt: "2026-07-05T14:00:00Z",
    updatedAt: "2026-07-09T16:30:00Z",
    lastMessage: {
      id: "msg-010",
      chatId: "chat-002",
      senderId: "user-002",
      senderName: "Vikram Reddy",
      senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
      content: "Sure, the flat is available from August 1st. Security deposit is ₹1,00,000.",
      type: "text",
      isRead: true,
      sentAt: "2026-07-09T16:30:00Z",
    },
  },
];

export const mockMessages: Message[] = [
  {
    id: "msg-001",
    chatId: "chat-001",
    senderId: "user-006",
    senderName: "Priya Mehta",
    senderAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    content: "Hi, I'm interested in the Rushikonda villa. Is it still available?",
    type: "text",
    isRead: true,
    sentAt: "2026-07-08T10:00:00Z",
  },
  {
    id: "msg-002",
    chatId: "chat-001",
    senderId: "user-002",
    senderName: "Vikram Reddy",
    senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    content: "Hello Priya! Yes, the villa is available. It's a stunning property with direct sea views.",
    type: "text",
    isRead: true,
    sentAt: "2026-07-08T10:15:00Z",
  },
  {
    id: "msg-003",
    chatId: "chat-001",
    senderId: "user-006",
    senderName: "Priya Mehta",
    senderAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    content: "The price seems a bit high. Is there any room for negotiation?",
    type: "text",
    isRead: true,
    sentAt: "2026-07-09T11:00:00Z",
  },
  {
    id: "msg-004",
    chatId: "chat-001",
    senderId: "user-002",
    senderName: "Vikram Reddy",
    senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    content: "I appreciate your interest. We can discuss the price during the site visit. The property speaks for itself!",
    type: "text",
    isRead: true,
    sentAt: "2026-07-09T11:30:00Z",
  },
  {
    id: "msg-005",
    chatId: "chat-001",
    senderId: "user-006",
    senderName: "Priya Mehta",
    senderAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    content: "Can we schedule a visit this weekend? Saturday morning works best for me.",
    type: "text",
    isRead: false,
    sentAt: "2026-07-10T09:15:00Z",
  },
];

// ============================================================================
// MOCK LEADS
// ============================================================================

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    propertyId: "prop-001",
    propertyTitle: "Luxury 4BHK Sea View Villa in Rushikonda",
    propertyImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&q=80",
    buyerId: "user-006",
    buyerName: "Priya Mehta",
    buyerPhone: "9876500001",
    buyerEmail: "priya.mehta@gmail.com",
    message: "Very interested in the sea view villa. Would like to schedule a visit.",
    status: "interested",
    source: "contact-form",
    createdAt: "2026-07-08T10:00:00Z",
    updatedAt: "2026-07-09T11:00:00Z",
  },
  {
    id: "lead-002",
    propertyId: "prop-003",
    propertyTitle: "2BHK Furnished Flat for Rent, Madhurawada",
    propertyImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&q=80",
    buyerId: "user-007",
    buyerName: "Amit Kumar",
    buyerPhone: "9876500002",
    buyerEmail: "amit.kumar@outlook.com",
    message: "Looking for immediate occupancy. Can I visit tomorrow?",
    status: "contacted",
    source: "whatsapp",
    createdAt: "2026-07-05T14:00:00Z",
    updatedAt: "2026-07-09T16:30:00Z",
  },
  {
    id: "lead-003",
    propertyId: "prop-001",
    propertyTitle: "Luxury 4BHK Sea View Villa in Rushikonda",
    propertyImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&q=80",
    buyerId: "user-008",
    buyerName: "Rajesh Nair",
    buyerPhone: "9876500003",
    buyerEmail: "rajesh.nair@company.com",
    message: "NRI buyer. Will be in Vizag next month. Please share more details.",
    status: "new",
    source: "contact-form",
    createdAt: "2026-07-10T06:00:00Z",
    updatedAt: "2026-07-10T06:00:00Z",
  },
];

// ============================================================================
// MOCK APPOINTMENTS
// ============================================================================

export const mockAppointments: Appointment[] = [
  {
    id: "apt-001",
    propertyId: "prop-001",
    propertyTitle: "Luxury 4BHK Sea View Villa in Rushikonda",
    propertyImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&q=80",
    buyerId: "user-006",
    buyerName: "Priya Mehta",
    ownerId: "user-002",
    ownerName: "Vikram Reddy",
    date: "2026-07-13",
    time: "10:00 AM",
    type: "in-person",
    status: "confirmed",
    notes: "Client prefers morning visit. Has pre-approved home loan.",
    createdAt: "2026-07-10T09:30:00Z",
  },
  {
    id: "apt-002",
    propertyId: "prop-005",
    propertyTitle: "Premium 3BHK in Gachibowli Financial District",
    propertyImage: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80",
    buyerId: "user-008",
    buyerName: "Rajesh Nair",
    ownerId: "user-005",
    ownerName: "Srinivas Developers",
    date: "2026-07-15",
    time: "03:00 PM",
    type: "video",
    status: "pending",
    createdAt: "2026-07-09T14:00:00Z",
  },
];

// ============================================================================
// MOCK REVIEWS
// ============================================================================

export const mockReviews: Review[] = [
  {
    id: "review-001",
    agentId: "user-003",
    reviewerId: "user-006",
    reviewerName: "Priya Mehta",
    reviewerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    rating: 5,
    title: "Exceptional service and knowledge",
    content: "Sunita was incredibly helpful throughout the entire process. Her knowledge of the Bengaluru market is unmatched. She found us our dream home within our budget and timeline.",
    isVerified: true,
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "review-002",
    propertyId: "prop-001",
    reviewerId: "user-008",
    reviewerName: "Rajesh Nair",
    rating: 5,
    title: "Breathtaking views, worth every rupee",
    content: "Visited this villa during my trip to Vizag. The sea views are absolutely stunning. Well-maintained property with premium finishes. Highly recommend for luxury seekers.",
    isVerified: true,
    createdAt: "2026-05-20T10:00:00Z",
  },
  {
    id: "review-003",
    agentId: "user-003",
    reviewerId: "user-007",
    reviewerName: "Amit Kumar",
    rating: 4,
    title: "Very professional and responsive",
    content: "Sunita helped me find a great rental in Hyderabad. She was always available and responsive. Only minor delay in paperwork, otherwise perfect experience.",
    isVerified: true,
    createdAt: "2026-04-10T10:00:00Z",
  },
];

// ============================================================================
// TESTIMONIALS (for homepage)
// ============================================================================

export const mockTestimonials = [
  {
    id: "test-001",
    name: "Priya Mehta",
    role: "Home Buyer",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    city: "Bengaluru",
    quote: "ROAD FACING made finding our dream home effortless. The verified listings gave us confidence, and the agent matching was spot on. We closed on a beautiful villa in just 3 weeks!",
    rating: 5,
  },
  {
    id: "test-002",
    name: "Rajesh Nair",
    role: "NRI Investor",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80",
    city: "Dubai → Vizag",
    quote: "As an NRI, managing property search remotely was always stressful. ROAD FACING's verified listings and video tours changed everything. Invested in two properties from Dubai seamlessly.",
    rating: 5,
  },
  {
    id: "test-003",
    name: "Sunita Sharma",
    role: "Real Estate Agent",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    city: "Hyderabad",
    quote: "ROAD FACING transformed my business. The lead management system is incredible — I've 3x'd my closings since joining. The platform feels premium, which impresses my clients.",
    rating: 5,
  },
  {
    id: "test-004",
    name: "Vikram Reddy",
    role: "Property Owner",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    city: "Visakhapatnam",
    quote: "Listed my properties on 5 platforms. ROAD FACING consistently delivers the best quality leads. The verification badge builds trust instantly — buyers approach with serious intent.",
    rating: 5,
  },
];

// ============================================================================
// TRENDING LOCATIONS
// ============================================================================

export const mockTrendingLocations = [
  { city: "Vijayawada", locality: "Benz Circle", image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=600&q=80", trendPercent: 24, avgPrice: 8500, totalListings: 145 },
  { city: "Vijayawada", locality: "Patamata", image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80", trendPercent: 18, avgPrice: 7200, totalListings: 123 },
  { city: "Guntur", locality: "Brodipet", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80", trendPercent: 15, avgPrice: 5800, totalListings: 112 },
  { city: "Amaravati", locality: "Capital Region", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80", trendPercent: 32, avgPrice: 4500, totalListings: 338 },
  { city: "Mangalagiri", locality: "Mangalagiri IT Park", image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80", trendPercent: 29, avgPrice: 6500, totalListings: 187 },
  { city: "Vijayawada", locality: "Autonagar", image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&q=80", trendPercent: 11, avgPrice: 4700, totalListings: 88 },
];

// ============================================================================
// BLOG POSTS
// ============================================================================

export const mockBlogPosts = [
  {
    id: "blog-001",
    slug: "rera-guide-india-2026",
    title: "Complete RERA Guide for Indian Homebuyers in 2026",
    excerpt: "Everything you need to know about RERA verification, compliance, and how to check if your builder is RERA registered.",
    image: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=600&q=80",
    category: "Guides",
    author: "ROAD FACING Editorial",
    readTime: "8 min read",
    publishedAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "blog-002",
    slug: "best-localities-vizag-2026",
    title: "Top 10 Localities to Buy Property in Visakhapatnam",
    excerpt: "From beachside Rushikonda to the IT hub Madhurawada — discover where smart buyers are investing in Vizag.",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=600&q=80",
    category: "Market Insights",
    author: "ROAD FACING Research",
    readTime: "6 min read",
    publishedAt: "2026-06-28T10:00:00Z",
  },
  {
    id: "blog-003",
    slug: "home-loan-tips-first-buyers",
    title: "Home Loan Tips: A First-Time Buyer's Complete Checklist",
    excerpt: "Interest rates, documentation, EMI planning, and common mistakes to avoid when applying for your first home loan in India.",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80",
    category: "Finance",
    author: "ROAD FACING Finance",
    readTime: "10 min read",
    publishedAt: "2026-06-20T10:00:00Z",
  },
];

// ============================================================================
// SAVED SEARCHES
// ============================================================================

export const mockSavedSearches = [
  {
    id: "ss-001",
    userId: "user-002",
    name: "Villas in Rushikonda under ₹1Cr",
    filters: {
      listingType: "sale" as const,
      propertyTypes: ["villa" as const],
      city: "Visakhapatnam",
      locality: "Rushikonda",
      maxPrice: 10000000,
    },
    alertEnabled: true,
    alertFrequency: "daily" as const,
    createdAt: "2026-06-01T10:00:00Z",
    lastNotifiedAt: "2026-07-10T06:00:00Z",
  },
  {
    id: "ss-002",
    userId: "user-002",
    name: "3BHK Apartments in Gachibowli",
    filters: {
      listingType: "sale" as const,
      propertyTypes: ["apartment" as const],
      city: "Hyderabad",
      locality: "Gachibowli",
      bedrooms: [3],
    },
    alertEnabled: true,
    alertFrequency: "weekly" as const,
    createdAt: "2026-05-15T10:00:00Z",
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getPropertyBySlug(slug: string): Property | undefined {
  return mockProperties.find((p) => p.slug === slug);
}

export function getPropertiesByCity(city: string): Property[] {
  return mockProperties.filter(
    (p) => p.location.city.toLowerCase() === city.toLowerCase()
  );
}

export function getFeaturedProperties(): Property[] {
  return mockProperties.filter((p) => p.isFeatured);
}

export function getLuxuryProperties(): Property[] {
  return mockProperties.filter((p) => p.price >= 50000000 && p.listingType === "sale");
}

export function getRecentProperties(limit: number = 8): Property[] {
  return [...mockProperties]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
}

export function getPropertiesByType(type: string): Property[] {
  return mockProperties.filter((p) => p.listingType === type);
}

export function getRentalProperties(): Property[] {
  return mockProperties.filter((p) => p.listingType === "rent" || p.listingType === "pg");
}

export function getUserById(id: string): UserProfile | undefined {
  return mockUsers.find((u) => u.id === id);
}

export function filterProperties(
  filters: Partial<{
    listingType: string;
    propertyTypes: string[];
    city: string;
    minPrice: number;
    maxPrice: number;
    bedrooms: number[];
    isReraVerified: boolean;
  }>
): Property[] {
  return mockProperties.filter((p) => {
    if (filters.listingType && p.listingType !== filters.listingType) return false;
    if (filters.propertyTypes?.length && !filters.propertyTypes.includes(p.propertyType)) return false;
    if (filters.city && p.location.city.toLowerCase() !== filters.city.toLowerCase()) return false;
    if (filters.minPrice !== undefined && p.price < filters.minPrice) return false;
    if (filters.maxPrice !== undefined && p.price > filters.maxPrice) return false;
    if (filters.bedrooms?.length && !filters.bedrooms.includes(p.bedrooms)) return false;
    if (filters.isReraVerified && !p.reraId) return false;
    return true;
  });
}

