export const siteConfig = {
  name: "ROAD FACING",
  fullName: "Real Owner Agent Developer",
  description:
    "India's most premium real estate platform. Buy, sell, rent properties across India with verified listings, AI-powered search, and trusted agents.",
  url: "https://road.in",
  ogImage: "/og-image.png",
  locale: "en-IN",
  currency: "INR",
  country: "India",
  phone: "+91 98765 43210",
  email: "hello@road.in",
  socials: {
    twitter: "https://twitter.com/road_in",
    instagram: "https://instagram.com/road.in",
    linkedin: "https://linkedin.com/company/road-in",
    youtube: "https://youtube.com/@road-in",
    facebook: "https://facebook.com/road.in",
  },
  keywords: [
    "real estate India",
    "buy property India",
    "rent apartment",
    "flat for sale",
    "villa for sale",
    "plot for sale",
    "PG accommodation",
    "commercial space",
    "RERA verified",
    "property listing",
    "Hyderabad real estate",
    "Bengaluru apartments",
    "Mumbai flats",
    "Delhi NCR property",
    "Chennai homes",
    "Visakhapatnam real estate",
  ],
} as const;

export const propertyTypeLabels: Record<string, string> = {
  apartment: "Apartment / Flat",
  villa: "Villa",
  "independent-house": "Independent House",
  plot: "Plot / Land",
  commercial: "Commercial Space",
  "pg-coliving": "PG / Co-living",
  farmhouse: "Farmhouse",
};

export const listingTypeLabels: Record<string, string> = {
  sale: "Buy",
  rent: "Rent",
  pg: "PG / Co-living",
};

export const furnishingLabels: Record<string, string> = {
  furnished: "Fully Furnished",
  "semi-furnished": "Semi Furnished",
  unfurnished: "Unfurnished",
};

export const facingLabels: Record<string, string> = {
  north: "North",
  south: "South",
  east: "East",
  west: "West",
  "north-east": "North East",
  "north-west": "North West",
  "south-east": "South East",
  "south-west": "South West",
};

export const priceTiers = {
  sale: [
    { label: "Under ₹25L", min: 0, max: 2500000 },
    { label: "₹25L – ₹50L", min: 2500000, max: 5000000 },
    { label: "₹50L – ₹1Cr", min: 5000000, max: 10000000 },
    { label: "₹1Cr – ₹2Cr", min: 10000000, max: 20000000 },
    { label: "₹2Cr – ₹5Cr", min: 20000000, max: 50000000 },
    { label: "₹5Cr+", min: 50000000, max: Infinity },
  ],
  rent: [
    { label: "Under ₹10K", min: 0, max: 10000 },
    { label: "₹10K – ₹20K", min: 10000, max: 20000 },
    { label: "₹20K – ₹50K", min: 20000, max: 50000 },
    { label: "₹50K – ₹1L", min: 50000, max: 100000 },
    { label: "₹1L+", min: 100000, max: Infinity },
  ],
} as const;

export const indianCities = [
  {
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    localities: [
      "Rushikonda",
      "MVP Colony",
      "Madhurawada",
      "Gajuwaka",
      "Seethammadhara",
      "Dwaraka Nagar",
      "Beach Road",
      "Kommadi",
      "Pendurthi",
      "NAD Junction",
    ],
  },
  {
    name: "Hyderabad",
    state: "Telangana",
    localities: [
      "Gachibowli",
      "Hitech City",
      "Banjara Hills",
      "Jubilee Hills",
      "Kondapur",
      "Madhapur",
      "Kukatpally",
      "Begumpet",
      "Manikonda",
      "Miyapur",
    ],
  },
  {
    name: "Bengaluru",
    state: "Karnataka",
    localities: [
      "Whitefield",
      "Koramangala",
      "Indiranagar",
      "HSR Layout",
      "Electronic City",
      "Marathahalli",
      "Hebbal",
      "Sarjapur Road",
      "JP Nagar",
      "Bannerghatta Road",
    ],
  },
  {
    name: "Chennai",
    state: "Tamil Nadu",
    localities: [
      "Adyar",
      "Anna Nagar",
      "T. Nagar",
      "Velachery",
      "OMR",
      "Porur",
      "Tambaram",
      "Sholinganallur",
      "Thiruvanmiyur",
      "ECR",
    ],
  },
  {
    name: "Mumbai",
    state: "Maharashtra",
    localities: [
      "Bandra",
      "Andheri",
      "Powai",
      "Worli",
      "Juhu",
      "Malad",
      "Goregaon",
      "Thane",
      "Navi Mumbai",
      "Borivali",
    ],
  },
  {
    name: "Delhi NCR",
    state: "Delhi",
    localities: [
      "Gurugram",
      "Noida",
      "Greater Noida",
      "Dwarka",
      "Vasant Kunj",
      "Saket",
      "Defence Colony",
      "Hauz Khas",
      "Greater Kailash",
      "Faridabad",
    ],
  },
] as const;

export const amenitiesList = [
  { id: "power-backup", name: "Power Backup", icon: "Zap", category: "utility" as const },
  { id: "lift", name: "Lift", icon: "ArrowUpDown", category: "basic" as const },
  { id: "gated-security", name: "Gated Security", icon: "Shield", category: "safety" as const },
  { id: "vastu-compliant", name: "Vastu Compliant", icon: "Compass", category: "basic" as const },
  { id: "clubhouse", name: "Clubhouse", icon: "Building2", category: "lifestyle" as const },
  { id: "covered-parking", name: "Covered Parking", icon: "Car", category: "parking" as const },
  { id: "water-supply", name: "24x7 Water Supply", icon: "Droplets", category: "utility" as const },
  { id: "maintenance-staff", name: "Maintenance Staff", icon: "Wrench", category: "society" as const },
  { id: "gym", name: "Gymnasium", icon: "Dumbbell", category: "lifestyle" as const },
  { id: "swimming-pool", name: "Swimming Pool", icon: "Waves", category: "lifestyle" as const },
  { id: "park", name: "Park / Garden", icon: "Trees", category: "lifestyle" as const },
  { id: "cctv", name: "CCTV Surveillance", icon: "Camera", category: "safety" as const },
  { id: "intercom", name: "Intercom", icon: "Phone", category: "safety" as const },
  { id: "fire-safety", name: "Fire Safety", icon: "Flame", category: "safety" as const },
  { id: "childrens-play-area", name: "Children's Play Area", icon: "Baby", category: "lifestyle" as const },
  { id: "jogging-track", name: "Jogging Track", icon: "Footprints", category: "lifestyle" as const },
  { id: "rainwater-harvesting", name: "Rainwater Harvesting", icon: "CloudRain", category: "utility" as const },
  { id: "solar-panels", name: "Solar Panels", icon: "Sun", category: "utility" as const },
  { id: "visitor-parking", name: "Visitor Parking", icon: "ParkingCircle", category: "parking" as const },
  { id: "indoor-games", name: "Indoor Games Room", icon: "Gamepad2", category: "lifestyle" as const },
  { id: "community-hall", name: "Community Hall", icon: "Users", category: "society" as const },
  { id: "piped-gas", name: "Piped Gas", icon: "Flame", category: "utility" as const },
  { id: "ev-charging", name: "EV Charging Point", icon: "PlugZap", category: "parking" as const },
  { id: "sports-facility", name: "Sports Facility", icon: "Trophy", category: "lifestyle" as const },
] as const;

export const navigationLinks = {
  main: [
    { label: "Buy", href: "/properties?type=sale" },
    { label: "Rent", href: "/properties?type=rent" },
    { label: "Commercial", href: "/commercial" },
    { label: "New Projects", href: "/new-projects" },
    { label: "Agents", href: "/agents" },
  ],
  footer: {
    company: [
      { label: "About Us", href: "/about" },
      { label: "Careers", href: "/careers" },
      { label: "Blog", href: "/blog" },
      { label: "Contact Us", href: "/contact" },
      { label: "Press", href: "/press" },
    ],
    forBuyers: [
      { label: "Browse Properties", href: "/properties" },
      { label: "Home Loans", href: "/mortgage-calculator" },
      { label: "EMI Calculator", href: "/mortgage-calculator" },
      { label: "Property Guides", href: "/blog" },
      { label: "RERA Check", href: "/rera-check" },
    ],
    forOwners: [
      { label: "Post Property", href: "/dashboard/listings/new" },
      { label: "Owner Dashboard", href: "/dashboard" },
      { label: "Pricing Plans", href: "/pricing" },
      { label: "Verification", href: "/dashboard/listings/verification" },
      { label: "Owner Guides", href: "/blog" },
    ],
    forAgents: [
      { label: "Agent Registration", href: "/register?role=agent" },
      { label: "Agent Dashboard", href: "/dashboard" },
      { label: "Lead Management", href: "/dashboard/listings/leads" },
      { label: "Agent Plans", href: "/pricing" },
      { label: "Agent Resources", href: "/blog" },
    ],
    cities: [
      { label: "Visakhapatnam", href: "/properties?city=visakhapatnam" },
      { label: "Hyderabad", href: "/properties?city=hyderabad" },
      { label: "Bengaluru", href: "/properties?city=bengaluru" },
      { label: "Chennai", href: "/properties?city=chennai" },
      { label: "Mumbai", href: "/properties?city=mumbai" },
      { label: "Delhi NCR", href: "/properties?city=delhi-ncr" },
    ],
    legal: [
      { label: "Privacy Policy", href: "/privacy" },
      { label: "Terms of Service", href: "/terms" },
      { label: "Cookie Policy", href: "/cookies" },
      { label: "Disclaimer", href: "/disclaimer" },
      { label: "Grievance Redressal", href: "/grievance" },
    ],
  },
} as const;
